apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ksox

resources:
  - ./../../resources
  - ./certificates.yaml
  - ./issuer.yaml
  - ./redis.yaml
  - ./surrealdb.yaml

patches:
  - path: surrealdb.patch.yaml
    target:
      kind: Deployment
      labelSelector: "app=surrealdb"

secretGenerator:
  - name: surrealdb-secrets
    env: ./envs/surrealdb-secrets.env

configMapGenerator:
  - name: surrealdb-config
    env: ./envs/surrealdb-config.env

generatorOptions:
  disableNameSuffixHash: true
