name: Prettier Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  prettier:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npx prettier --check .
